### ISSUE TITLE
Overhaul default content.htm

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#179]
The shipped content.htm has to reflect all relevant changes made for XH 1.7:

* [ ] [Powered by links](https://github.com/cmsimple-xh/cmsimple-xh/issues/59) instead of backlinks to cmsimple-xh.org
* [x] "Menu Levels and Headings" has to reflect the [new split mode](https://github.com/cmsimple-xh/cmsimple-xh/issues/162). It might be good to change the substructure of this page to single subpages nested down to the maximum level (i.e. 9).
* [x] The subpages of "Templates and Plugins" will have to be adapted to the [new templates](https://github.com/cmsimple-xh/cmsimple-xh/issues/68).
* [x] The actual headings of the newsbox pages should be changed to `<h2>`, so we get a clean heading structure.

Of course, we must not forget to update the 2lang content.htm accordingly.

**Comment by cmb69** [comment]
I suggest to merge PR #229 to adress item 4 in the list above.

**Comment by cmb69** [comment]
Actually, the first item in the list above (powered-by-links instead of template-designer-backlinks) isn't a content issues, but rather a template issue, so I'm closing this ticket.
