### ISSUE TITLE
CMSimple_XH 1.7.6 TODO

### ISSUE THREAD

**Issue by olape-git** [cmsimple-xh/cmsimple-xh#579]
- [x] update version.nfo
- [x] update [cmsimple-xh.org](https://cmsimple-xh.org) -> download, content (php-version), changelog
- [x] update [wiki.cmsimple-xh.org](https://wiki.cmsimple-xh.org) -> content (php-version)
- [x] update [demo.cmsimple-xh.org](https://demo.cmsimple-xh.org) -> CMS
- [ ] update [wiki.cmsimple-xh.org](https://demo.cmsimple-xh.org/) -> CMS
- [ ] update [www.cmsimple-xh.org](https://demo.cmsimple-xh.org/) -> CMS
- [x] additional announcement in forum? (a "normal" announcement under [General Discussions & Announcements](https://cmsimpleforum.com/viewforum.php?f=2))
- [x] update [dev-doc.cmsimple-xh.org](https://dev-doc.cmsimple-xh.org)
- [x] [update heise](https://www.heise.de/download/product/cmsimple-xh-91863)
- [x] [publish the final version hi_updatecheck](https://github.com/cmsimple-xh/hi_updatecheck/releases)
- [x] [publish the final version jQuery_XH](https://github.com/cmsimple-xh/jQuery_XH/releases)

further information under [release_a_new_version](https://wiki.cmsimple-xh.org/archiv/doku.php/release_a_new_version)
